env:
  browser: true
  es6: true
  node: true
  mocha: true
extends:
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
  - jsx-a11y
rules:
  react/forbid-prop-types: 0
  import/prefer-default-export: 1
  import/no-extraneous-dependencies: 1
