env:
  browser: true
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:mocha/recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - mocha
  - react
  - jsx-a11y
  - prettier
settings:
  react:
    version: detect
rules:
  no-var: 2
  jsx-a11y/no-onchange: 0
